In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('framingham_heart_disease.csv') #adding data

dataset = pd.DataFrame(dataset)
#print 1st 5 rows
dataset.head()
# dataset.shape

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [55]:
dataset.isnull().sum()
dataset.dtypes

male                 int64
age                  int64
education          float64
currentSmoker        int64
cigsPerDay         float64
BPMeds             float64
prevalentStroke      int64
prevalentHyp         int64
diabetes             int64
totChol            float64
sysBP              float64
diaBP              float64
BMI                float64
heartRate          float64
glucose            float64
TenYearCHD           int64
dtype: object

In [57]:
data = dataset.drop(['education','BPMeds','totChol','BMI','glucose','heartRate' ], axis = 'columns')
data.head()

male  age  currentSmoker  cigsPerDay  prevalentStroke  prevalentHyp  \
0     1   39              0         0.0                0             0   
1     0   46              0         0.0                0             0   
2     1   48              1        20.0                0             0   
3     0   61              1        30.0                0             1   
4     0   46              1        23.0                0             0   

   diabetes  sysBP  diaBP  TenYearCHD  
0         0  106.0   70.0           0  
1         0  121.0   81.0           0  
2         0  127.5   80.0           0  
3         0  150.0   95.0           1  
4         0  130.0   84.0           0

In [86]:
cigarettes = data['cigsPerDay']
cigarettes.head()

0     0.0
1     0.0
2    20.0
3    30.0
4    23.0
Name: cigsPerDay, dtype: float64

In [85]:
cigarettes.fillna(round(cigarettes.mean()), inplace = True)
#hr.fillna(integer_value, inplace = True)
data.isnull().sum()

male               0
age                0
currentSmoker      0
cigsPerDay         0
prevalentStroke    0
prevalentHyp       0
diabetes           0
sysBP              0
diaBP              0
TenYearCHD         0
dtype: int64

In [67]:
#this data is labeled data
#independent variable (X) will be Age, Estimated Salary
#dependent variable(y) will be Purcahsed (It will be lable)

#define X,y
X = dataset.iloc[:, [ 1, 3]].values
y = dataset.iloc[:, 15].values

#print X,y
print(X[:5, :])
print(y[:5])

[[39  0]
 [46  0]
 [48  1]
 [61  1]
 [46  1]]
[0 0 0 1 0]


In [68]:
#import train_test_split from sklearn to train and test our data
from sklearn.model_selection import train_test_split

#define
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
#print
print(X_train[:5],'\n', '\n', y_train[:5],'\n','\n', X_test[:5],'\n','\n', y_test[:5])

#create object of LogisticRegression class to refer as classifier
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

[[60  0]
 [42  1]
 [60  1]
 [67  0]
 [51  0]] 
 
 [0 0 1 1 0] 
 
 [[47  0]
 [58  0]
 [61  1]
 [45  0]
 [57  0]] 
 
 [0 0 0 0 0]


C:\Users\Afrid\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [69]:
#dataset.info()
#check corelation among attributes of dataset 
data.corr()

male       age  currentSmoker  cigsPerDay  \
male             1.000000 -0.028979       0.197596    0.316806   
age             -0.028979  1.000000      -0.213748   -0.192366   
currentSmoker    0.197596 -0.213748       1.000000    0.766968   
cigsPerDay       0.316806 -0.192366       0.766968    1.000000   
prevalentStroke -0.004546  0.057655      -0.032988   -0.032706   
prevalentHyp     0.005313  0.307194      -0.103260   -0.065947   
diabetes         0.015708  0.101258      -0.044295   -0.037063   
sysBP           -0.035989  0.394302      -0.130230   -0.088505   
diaBP            0.057933  0.206104      -0.107746   -0.056391   
TenYearCHD       0.088428  0.225256       0.019456    0.057775   

                 prevalentStroke  prevalentHyp  diabetes     sysBP     diaBP  \
male                   -0.004546      0.005313  0.015708 -0.035989  0.057933   
age                     0.057655      0.307194  0.101258  0.394302  0.206104   
currentSmoker          -0.032988     -0.103260 -0.044295 -0.130230 -0.107746   
cigsPerDay             -0.032706     -0.065947 -0.037063 -0.088505 -0.056391   
prevalentStroke         1.000000      0.074830  0.006949  0.057009  0.045190   
prevalentHyp            0.074830      1.000000  0.077808  0.696755  0.615751   
diabetes                0.006949      0.077808  1.000000  0.111283  0.050329   
sysBP                   0.057009      0.696755  0.111283  1.000000  0.784002   
diaBP                   0.045190      0.615751  0.050329  0.784002  1.000000   
TenYearCHD              0.061810      0.177603  0.097317  0.216429  0.145299   

                 TenYearCHD  
male               0.088428  
age                0.225256  
currentSmoker      0.019456  
cigsPerDay         0.057775  
prevalentStroke    0.061810  
prevalentHyp       0.177603  
diabetes           0.097317  
sysBP              0.216429  
diaBP              0.145299  
TenYearCHD         1.000000

In [113]:
#normalization and feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [114]:

print(X_train[:5], '\n','\n', X_test[:5])

[[ 1.16018135  0.27416264 -0.98013821 -0.75079239 -0.07895127 -0.65971538
  -0.16037022  0.15940265 -0.57741688]
 [ 1.16018135 -0.54387827  1.02026428  2.90987614 -0.07895127 -0.65971538
  -0.16037022  0.22700586  0.17676733]
 [-0.86193422 -0.77760425 -0.98013821 -0.75079239 -0.07895127 -0.65971538
  -0.16037022 -0.65183586 -0.49361864]
 [-0.86193422  0.74161459 -0.98013821 -0.75079239 -0.07895127 -0.65971538
  -0.16037022 -0.56169825  0.34436383]
 [-0.86193422  1.91024446 -0.98013821 -0.75079239 -0.07895127  1.51580519
  -0.16037022  2.45791176  0.42816207]] 
 
 [[ 1.12577959 -1.07969539 -1.02145656 -0.78777367 -0.06884284  1.39443338
  -0.17066404  0.44797222  2.1666585 ]
 [ 1.12577959 -0.15181934 -1.02145656 -0.78777367 -0.06884284  1.39443338
  -0.17066404  0.75159631  0.68525086]
 [ 1.12577959 -0.49977286  0.97899416 -0.38329796 -0.06884284  1.39443338
  -0.17066404  0.42461652  0.3466434 ]
 [-0.88827335  1.00802572 -1.02145656 -0.78777367 -0.06884284  1.39443338
  -0.17066404  2.

In [115]:
#create object of LogisticRegression class to refer as classifier
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

print(X_test[:5], '\n', '\n', y_pred[:5])

[[ 1.12577959 -1.07969539 -1.02145656 -0.78777367 -0.06884284  1.39443338
  -0.17066404  0.44797222  2.1666585 ]
 [ 1.12577959 -0.15181934 -1.02145656 -0.78777367 -0.06884284  1.39443338
  -0.17066404  0.75159631  0.68525086]
 [ 1.12577959 -0.49977286  0.97899416 -0.38329796 -0.06884284  1.39443338
  -0.17066404  0.42461652  0.3466434 ]
 [-0.88827335  1.00802572 -1.02145656 -0.78777367 -0.06884284  1.39443338
  -0.17066404  2.62005223  1.61642138]
 [-0.88827335  1.00802572  0.97899416  0.83012914 -0.06884284  1.39443338
  -0.17066404  1.28877739  0.89688052]] 
 
 [0 0 0 0 0]


C:\Users\Afrid\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [116]:
print(y_pred[:12],'\n','\n',y_test[:12])

[0 0 0 0 0 0 0 0 0 1 0 0] 
 
 3093    0
2285    0
1810    0
3883    0
3453    0
1873    0
3214    1
2532    0
3583    0
3136    1
2493    0
3631    0
Name: TenYearCHD, dtype: int64


In [117]:
#probability is 11/12 i.e 91.66% so, good to go

#we'll use a Confusion Matrix to evaluate exactly how accurate our Logistic Regression model is,
#the more the matching values, more is the accuracy

from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[726   7]
 [107   8]]


In [118]:
X = data[['male','age','currentSmoker','cigsPerDay','prevalentStroke','prevalentHyp','diabetes','sysBP','diaBP']]
y =  data['TenYearCHD']
X

male  age  currentSmoker  cigsPerDay  prevalentStroke  prevalentHyp  \
0        1   39              0         0.0                0             0   
1        0   46              0         0.0                0             0   
2        1   48              1        20.0                0             0   
3        0   61              1        30.0                0             1   
4        0   46              1        23.0                0             0   
...    ...  ...            ...         ...              ...           ...   
4233     1   50              1         1.0                0             1   
4234     1   51              1        43.0                0             0   
4235     0   48              1        20.0                0             0   
4236     0   44              1        15.0                0             0   
4237     0   52              0         0.0                0             0   

      diabetes  sysBP  diaBP  
0            0  106.0   70.0  
1            0  121.0   81.0  
2            0  127.5   80.0  
3            0  150.0   95.0  
4            0  130.0   84.0  
...        ...    ...    ...  
4233         0  179.0   92.0  
4234         0  126.5   80.0  
4235         0  131.0   72.0  
4236         0  126.5   87.0  
4237         0  133.5   83.0  

[4238 rows x 9 columns]

In [119]:
y

0       0
1       0
2       0
3       1
4       0
       ..
4233    1
4234    0
4235    0
4236    0
4237    0
Name: TenYearCHD, Length: 4238, dtype: int64

In [121]:
X = data[['male','age','currentSmoker','cigsPerDay','prevalentStroke','prevalentHyp','diabetes','sysBP','diaBP']]
y =  data['TenYearCHD']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20, random_state = 99)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train, y_train)
model.score(X_test,y_test)

C:\Users\Afrid\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.8702830188679245