### Load in NumPy (remember to pip install numpy first)

In [78]:
import numpy as np

### The Basics

In [79]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [80]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [81]:
# Get Dimension
a.ndim

1

In [82]:
# Get Shape
b.shape

(2, 3)

In [83]:
# Get Type
a.dtype

dtype('int32')

In [84]:
# Get data-Size
a.itemsize

4

In [85]:
# Get total size
a.nbytes

12

In [86]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [87]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [88]:
# Get a specific element [r, c]
a[1, 5]

13

In [89]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [90]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [91]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [92]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [93]:
# Flattens the n-dim array to 1D
a.ravel(), a.flatten()

(array([ 1,  2,  1,  4,  5,  6,  7,  8,  9,  2, 11, 12, 20, 14]),
 array([ 1,  2,  1,  4,  5,  6,  7,  8,  9,  2, 11, 12, 20, 14]))

In [ ]:
'''
(i)Return only reference/view of original array
(ii) If you modify the array you would notice that the value of original array also changes.
(iii) Ravel is faster than flatten() as it does not occupy any memory.
'''

In [144]:
p=np.arange(8).reshape(2,4)
print(p)
for columns in np.nditer(p, order='F'):
    print(columns)
    
for rows in np.nditer(p, order='C'):
    print('\t',rows)

[[0 1 2 3]
 [4 5 6 7]]
0
4
1
5
2
6
3
7
	 0
	 1
	 2
	 3
	 4
	 5
	 6
	 7


In [148]:
for rows in np.nditer(p, order='F', flags=['external_loop']):
    print(rows)

[0 4]
[1 5]
[2 6]
[3 7]


In [94]:
# distributes the value in between equally
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#### 3D example

In [95]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [96]:
# Get specific element (work outside in)
b[0,1,1]

4

In [97]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [98]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [99]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [100]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [101]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [102]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [103]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.92579988, 0.18241092],
       [0.38965019, 0.29305022],
       [0.7509202 , 0.88726525],
       [0.35254404, 0.68404323]])

In [104]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 7,  5, -1],
       [ 3, -3,  4],
       [ 5,  1,  7]])

In [105]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [106]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [107]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [108]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a, b)

[1 2 3] [100   2   3]


### Mathematics

In [109]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [110]:
a + 2

array([3, 4, 5, 6])

In [111]:
a - 2

array([-1,  0,  1,  2])

In [112]:
a * 2

array([2, 4, 6, 8])

In [113]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [114]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [115]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [116]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [117]:
# matrix multiplication
c=np.random.randint(1,10,size=(2,2))
d=np.random.randint(5,15,size=(2,2))
np.dot(c,d)

array([[78, 92],
       [78, 94]])

In [118]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [119]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [120]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [121]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [122]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
np.min(stats)

1

In [124]:
np.max(stats, axis=1)

array([3, 6])

In [125]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [126]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before, '\n'+'--------------')

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]] 
--------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [127]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [128]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

arr = np.hstack((h1,h2))

In [129]:
np.hsplit(arr, 3)

[array([[1., 1.],
        [1., 1.]]),
 array([[1., 1.],
        [1., 1.]]),
 array([[0., 0.],
        [0., 0.]])]

In [130]:
np.vsplit(arr,2)

[array([[1., 1., 1., 1., 0., 0.]]), array([[1., 1., 1., 1., 0., 0.]])]

In [131]:
a = np.random.randint(9, size=(3,3))
b = a>4
a,b,a[b]

(array([[6, 0, 0],
        [0, 7, 3],
        [0, 4, 1]]),
 array([[ True, False, False],
        [False,  True, False],
        [False, False, False]]),
 array([6, 7]))

### Miscellaneous
##### Load Data from File

In [132]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [133]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])